window.personajeDemo = {
  nombre: "Gerald",
  raza: "elfo",
  subraza: "altoelfo",
  clase1: "guerrero",
  nivelClase1: 1,
  subclase1: "",
  clase2: "",
  nivelClase2: 0,
  subclase2: "",
  clase3: "",
  nivelClase3: 0,
  subclase3: "",
  nivel: 1,
  FUE: 15,
  DES: 15,
  CON: 15,
  INT: 15,
  SAB: 15,
  CAR: 15,
  armadura: "",
  escudo: "",
  monedas: { cp: 130, sp: 0, ep: 0, gp: 0, pp: 0 },
  equipo: [],
  inventarioEquipo: [],
  sintonizacionSlots: 3,
  sintonizados: [],
  hpActual: 0,
  hpTemporales: 0,
  inspiracion: false,
  concentracion: false,
  estadosActivos: [],
  eleccionesRasgos: {},
  progresionNiveles: {},
  pgPorNivel: {}
};